### ISSUE TITLE
build error in flutter 1.10.15, ExtendedMemoryImageProvider.load' has fewer positional arguments than those of overridden method 'MemoryImage.load'.

### ISSUE THREAD

**Issue by mana-ai** [fluttercandies/extended_image#80]
pub.flutter-io.cn/extended_image_library-0.1.8/lib/src/extended_me
mory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has fewer positional arguments
than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key) {

**Comment by zmtzawqlp** [comment]
please use preview-version for now, i will fix it as soon as possible

**Comment by zmtzawqlp** [comment]
please provide version of flutter sdk  , i didn't see any problem from my side

**Comment by Codered81** [comment]
Cached_network_image package has the exact same issue, they provided an RC as a temporary fix due to the breaking change in Flutter SDK.

**Comment by zmtzawqlp** [comment]
ok, think, I see，i will fix it in dev branch as soon as possible. you can use it as git url

**Comment by zmtzawqlp** [comment]
please add following code to your pubspec.yaml for now. i have fixed build error in dev branch, i will publish it to pub.com when 1.10.15 is in stable branch
``` yaml
dependency_overrides:
  extended_image_library:
    git:
        url: https://github.com/fluttercandies/extended_image_library.git
        ref: dev
```

**Comment by ThinkDigitalSoftware** [comment]
> please add following code to your pubspec.yaml for now. i have fixed build error in dev branch, i will publish it to pub.com when 1.10.15 is in stable branch
> 
```yaml
dependency_overrides:
  extended_image_library:
    git:
        url: https://github.com/fluttercandies/extended_image_library.git
        ref: dev
```
Weird, when I get it from git like you mentioned, it pulls version 0.1.9 even though that's not what it says on that branch...

**Comment by zmtzawqlp** [comment]
@ThinkDigitalSoftware extended_image_library is 0.1.9 on dev branch

**Comment by hmilitar** [comment]
Hi my results after i did flutter pub get:

`! extended_image_library 0.1.9 from git https://github.com/fluttercandies/extended_image_library.git at c00560`

**Comment by hmilitar** [comment]
Is this issue resolved already? kindly post solution please... tried above...still getting same error as the title of the issue. Thanks!

**Comment by zmtzawqlp** [comment]
@hmilitar it's right. i will publish it to pub.com when 1.10.15 is in stable branch

**Comment by bambinoua** [comment]
> 
> 
> @hmilitar it's right. i will publish it to pub.com when 1.10.15 is in stable branch
> 
> dependency_overrides:
> extended_image_library:
> git:
> url: https://github.com/fluttercandies/extended_image_library.git
> ref: dev

Unfortunately this does not help! Still have the same crash. Flutter is 1.11.0

**Comment by zmtzawqlp** [comment]
double check your extended_image_library version , it should be 0.1.9 at your side.

**Comment by bambinoua** [comment]
> 
> 
> double check your extended_image_library version , it should be 0.1.9 at your side.

pubspec.lock shows 1.0.8. I commented extended_image and extended_image_library in pubspec.yaml to remove them from lock-file (maybe some caching) then I add them again. Version is 1.0.8.

**Comment by zmtzawqlp** [comment]
do you add following ??

![image](https://user-images.githubusercontent.com/16477333/69939205-3625c780-151a-11ea-96c6-c834418ad9d5.png)

**Comment by bambinoua** [comment]
> 
> 
> do you add following ??
I am sorry my mistake. I wrote **rev** instead **ref**. Now looks good. Thanks!

**Comment by OPY-bbt** [comment]
fixed?

**Comment by zmtzawqlp** [comment]
fixed version is on pub

**Comment by masashi-sutou** [comment]
I have same error in extend_image 0.6.8 and extend_image_library 1.0.9.

Although the argument type is specified, I don't think "DecoderCallback" is defined anywhere. 

What is DecoderCallback?

**Comment by zmtzawqlp** [comment]
double check your local version .remove lock and packages , run flutter packages get .@masashi-sutou

**Comment by masashi-sutou** [comment]
@zmtzawqlp Thank you for reply.

I try remove `pubspec.lock` and `run flutter packages get`, but have same error.

error | get packeages
:-: | :-:
<img src=https://user-images.githubusercontent.com/6649643/70589289-b59a5180-1c12-11ea-8eab-ba7de5d0dda4.png width=540/> | <img src=https://user-images.githubusercontent.com/6649643/70589476-27729b00-1c13-11ea-8f97-a0f37880a3f1.png width=540/>

**Comment by zmtzawqlp** [comment]
extended_image: 0.6.8  include extended_image_library 0.1.9  , it's fixed the build error

**Comment by zmtzawqlp** [comment]
and  I use Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale C.UTF-8).

you should not use lastest version of extended image, see more https://github.com/fluttercandies/extended_image/issues/89

**Comment by qq329401134** [comment]
windows  v1.9.1+hotfix.6 使用0.6.8依然会报错

**Comment by qq329401134** [comment]
/D:/Program%20Files/Flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {

我的这样提示   使用的flutter是1.9.1 hotfix.6  咋办

**Comment by zmtzawqlp** [comment]
> /D:/Program%20Files/Flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: 'DecoderCallback' isn't a type.
> ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
> 
> 我的这样提示 使用的flutter是1.9.1 hotfix.6 咋办

https://github.com/fluttercandies/extended_image/issues/89

**Comment by masashi-sutou** [comment]
@zmtzawqlp 

Thank you for maintaining this package.
Using the latest stable channel `1.12.13 + hotfix .5`, the latest extended_image `0.6.8` and extended_image_library` 0.1.9` were successfully built.

**Comment by Tayeb-Ali** [comment]
any help sam error

```
> 
Compiler message:
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.1/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../development/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.
```

i try all
